-- AlterTable
ALTER TABLE "Consultant" ALTER COLUMN "phone" SET DATA TYPE TEXT,
ALTER COLUMN "postcode" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "phone" SET DATA TYPE TEXT,
ALTER COLUMN "postcode" SET DATA TYPE TEXT;
